phrases = [
    "Taking my dog for a walk is fun",
    "Walking in the rain can be difficult",
    "Strolling along a beach at sunset is romantic",
    "Getting a promotion is exciting",
    "Signing autographs takes time",
    "Going for ice cream is a real treat",
    "Singing for his supper was how he earned his keep",
    "Getting a sore back was the result of the golf game",
    "Pulling an all-nighter did not improve his test scores",
    "Sailing into the sunset was the perfect end to the book",
    "To make lemonade, you have to start with lemons",
    "I tried to see the stage, but I was too short",
    "She organized a boycott to make a statement",
    "To see Niagara Falls is mind-boggling",
    "He really needs to get his priorities in order",
    "The company decided to reduce hours for everyone",
    "To donate time or money is an honorable thing",
    "I went to Spain to study the language and culture",
    "Ogre",
    "Jungle",
    "Pickly",
    "Large",
    "Orange",
    "Cake",
    "Walk",
    "Green"
]